"""Alembic migration environment for AgentScope.

The database URL and target metadata are taken directly from the application so
migrations always match the models the app runs against:

* ``target_metadata`` is the Flask-SQLAlchemy metadata, populated by importing
  the models package (no running app / no ``create_all`` side effects needed).
* the URL comes from :class:`app.config.Config`, which reads ``DATABASE_URL``
  (and normalizes ``postgres://`` -> ``postgresql://``) or falls back to SQLite.

``render_as_batch=True`` enables SQLite-compatible ALTER statements so future
autogenerated migrations run on both SQLite and PostgreSQL.
"""
from logging.config import fileConfig

from alembic import context
from sqlalchemy import create_engine

# Import the app package so ``app.*`` is importable (prepend_sys_path = . puts
# the backend directory on sys.path when Alembic is run from there).
import app.models  # noqa: F401  (registers every model with db.metadata)
from app.config import Config
from app.extensions import db

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = db.metadata


def _database_url() -> str:
    """Resolve the same database URL the application uses."""
    return Config.SQLALCHEMY_DATABASE_URI


def run_migrations_offline() -> None:
    """Emit SQL to stdout without a live DB connection (``--sql`` mode)."""
    context.configure(
        url=_database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=True,
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations against a live database connection."""
    engine = create_engine(_database_url())
    try:
        with engine.connect() as connection:
            context.configure(
                connection=connection,
                target_metadata=target_metadata,
                render_as_batch=True,
                compare_type=True,
            )
            with context.begin_transaction():
                context.run_migrations()
    finally:
        engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
