"""add organization_id to traces and conversation_runs

Revision ID: 079078dbceb7
Revises: b3521d2e6aa3
Create Date: 2026-07-09 18:01:47.733056
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079078dbceb7'
down_revision: Union[str, None] = 'b3521d2e6aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Batch mode (SQLite) requires named constraints, so the foreign keys are
    # named explicitly here.
    with op.batch_alter_table('conversation_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_conversation_runs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_conversation_runs_organization_id', 'organizations',
            ['organization_id'], ['id'], ondelete='SET NULL',
        )

    with op.batch_alter_table('traces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_traces_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_traces_organization_id', 'organizations',
            ['organization_id'], ['id'], ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traces', schema=None) as batch_op:
        batch_op.drop_constraint('fk_traces_organization_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_traces_organization_id'))
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('conversation_runs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversation_runs_organization_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_conversation_runs_organization_id'))
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###
