"""initial schema

Revision ID: b3521d2e6aa3
Revises:
Create Date: 2026-07-09 17:48:30.361762
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3521d2e6aa3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('retrieved_documents', sa.JSON(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('final_response', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traces_model_name'), ['model_name'], unique=False)
        batch_op.create_index('ix_traces_model_timestamp', ['model_name', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_traces_status'), ['status'], unique=False)
        batch_op.create_index('ix_traces_status_timestamp', ['status', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_traces_timestamp'), ['timestamp'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('workflow_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=60), nullable=True),
    sa.Column('workflow_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_definitions_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_workflow_definitions_name_version', ['workflow_name', 'version'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_definitions_workflow_name'), ['workflow_name'], unique=False)

    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('parent_run_id', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('agent_type', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_agent_type'), ['agent_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_parent_run_id'), ['parent_run_id'], unique=False)
        batch_op.create_index('ix_agent_runs_request_created', ['request_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_status'), ['status'], unique=False)
        batch_op.create_index('ix_agent_runs_status_created', ['status', 'created_at'], unique=False)

    op.create_table('conversation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_trace_id', sa.Integer(), nullable=False),
    sa.Column('conversation_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_trace_id'], ['traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_conversation_runs_request_created', ['request_trace_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_runs_request_trace_id'), ['request_trace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_runs_status'), ['status'], unique=False)
        batch_op.create_index('ix_conversation_runs_status_created', ['status', 'created_at'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_membership_user_org')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index('ix_memberships_org_role', ['organization_id', 'role'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_project_org_slug')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_organization_id'), ['organization_id'], unique=False)

    op.create_table('agent_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_run_id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=True),
    sa.Column('parent_node_id', sa.Integer(), nullable=True),
    sa.Column('agent_role', sa.String(length=120), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('execution_order', sa.Integer(), nullable=True),
    sa.Column('parallel_group', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_run_id'], ['conversation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_node_id'], ['agent_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_nodes_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index('ix_agent_nodes_conversation_order', ['conversation_run_id', 'execution_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_nodes_conversation_run_id'), ['conversation_run_id'], unique=False)
        batch_op.create_index('ix_agent_nodes_conversation_status', ['conversation_run_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_nodes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_nodes_execution_order'), ['execution_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_nodes_parallel_group'), ['parallel_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_nodes_parent_node_id'), ['parent_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_nodes_status'), ['status'], unique=False)

    op.create_table('agent_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('step_type', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('input', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_steps_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_steps_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_agent_steps_run_number', ['agent_run_id', 'step_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_steps_status'), ['status'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_keys_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_prefix'), ['prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_revoked'), ['revoked'], unique=False)

    op.create_table('evaluation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_run_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_type', sa.String(length=120), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_run_id'], ['conversation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_runs', schema=None) as batch_op:
        batch_op.create_index('ix_evaluation_runs_conversation_created', ['conversation_run_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_runs_conversation_run_id'), ['conversation_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_runs_evaluation_type'), ['evaluation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_runs_status'), ['status'], unique=False)
        batch_op.create_index('ix_evaluation_runs_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_evaluation_runs_type_created', ['evaluation_type', 'created_at'], unique=False)

    op.create_table('model_comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_run_id', sa.Integer(), nullable=False),
    sa.Column('model_a', sa.String(length=255), nullable=True),
    sa.Column('model_b', sa.String(length=255), nullable=True),
    sa.Column('winner', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('cost_difference', sa.Float(), nullable=True),
    sa.Column('latency_difference', sa.Float(), nullable=True),
    sa.Column('token_difference', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_run_id'], ['conversation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_comparisons', schema=None) as batch_op:
        batch_op.create_index('ix_model_comparisons_conversation_created', ['conversation_run_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_comparisons_conversation_run_id'), ['conversation_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_comparisons_created_at'), ['created_at'], unique=False)

    op.create_table('prompt_assemblies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('conversation_context', sa.Text(), nullable=True),
    sa.Column('retrieved_context', sa.Text(), nullable=True),
    sa.Column('memory_context', sa.Text(), nullable=True),
    sa.Column('user_prompt', sa.Text(), nullable=True),
    sa.Column('assembled_prompt', sa.Text(), nullable=True),
    sa.Column('system_tokens', sa.Integer(), nullable=True),
    sa.Column('conversation_tokens', sa.Integer(), nullable=True),
    sa.Column('retrieval_tokens', sa.Integer(), nullable=True),
    sa.Column('memory_tokens', sa.Integer(), nullable=True),
    sa.Column('user_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_assemblies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_assemblies_agent_run_id'), ['agent_run_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_prompt_assemblies_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_prompt_assemblies_run', ['agent_run_id'], unique=False)

    op.create_table('prompt_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_versions_agent_run_id'), ['agent_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_versions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_versions_hash'), ['hash'], unique=False)
        batch_op.create_index('ix_prompt_versions_run_version', ['agent_run_id', 'version'], unique=False)

    op.create_table('replay_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_conversation_run_id', sa.Integer(), nullable=False),
    sa.Column('replayed_model', sa.String(length=255), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('system_prompt_override', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['original_conversation_run_id'], ['conversation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('replay_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_replay_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_replay_runs_original_conversation_run_id'), ['original_conversation_run_id'], unique=False)
        batch_op.create_index('ix_replay_runs_original_created', ['original_conversation_run_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_replay_runs_status'), ['status'], unique=False)
        batch_op.create_index('ix_replay_runs_status_created', ['status', 'created_at'], unique=False)

    op.create_table('workflow_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_definition_id', sa.Integer(), nullable=False),
    sa.Column('conversation_run_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_run_id'], ['conversation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_definition_id'], ['workflow_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_executions_conversation_run_id'), ['conversation_run_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_workflow_executions_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_workflow_executions_definition_status', ['workflow_definition_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_executions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_executions_workflow_definition_id'), ['workflow_definition_id'], unique=False)

    op.create_table('agent_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_run_id', sa.Integer(), nullable=True),
    sa.Column('sender_node_id', sa.Integer(), nullable=False),
    sa.Column('receiver_node_id', sa.Integer(), nullable=True),
    sa.Column('reply_to_id', sa.Integer(), nullable=True),
    sa.Column('message_type', sa.String(length=120), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_run_id'], ['conversation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_node_id'], ['agent_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['agent_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_node_id'], ['agent_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.create_index('ix_agent_messages_conversation_created', ['conversation_run_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_conversation_run_id'), ['conversation_run_id'], unique=False)
        batch_op.create_index('ix_agent_messages_conversation_type', ['conversation_run_id', 'message_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_message_type'), ['message_type'], unique=False)
        batch_op.create_index('ix_agent_messages_receiver_created', ['receiver_node_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_receiver_node_id'), ['receiver_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_reply_to_id'), ['reply_to_id'], unique=False)
        batch_op.create_index('ix_agent_messages_sender_created', ['sender_node_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_sender_node_id'), ['sender_node_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=True),
    sa.Column('target_id', sa.String(length=80), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_org_created', ['organization_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)

    op.create_table('evaluation_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_run_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_metrics_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_metrics_evaluation_run_id'), ['evaluation_run_id'], unique=False)
        batch_op.create_index('ix_evaluation_metrics_run_name', ['evaluation_run_id', 'metric_name'], unique=False)

    op.create_table('memory_accesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('memory_type', sa.String(length=120), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('retrieved_text', sa.Text(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['step_id'], ['agent_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_accesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_accesses_step_id'), ['step_id'], unique=False)

    op.create_table('retriever_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('retrieved_documents', sa.JSON(), nullable=True),
    sa.Column('embedding_time_ms', sa.Float(), nullable=True),
    sa.Column('retrieval_time_ms', sa.Float(), nullable=True),
    sa.Column('num_documents', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['step_id'], ['agent_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retriever_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retriever_traces_step_id'), ['step_id'], unique=False)

    op.create_table('tool_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['agent_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_executions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_executions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_executions_step_id'), ['step_id'], unique=False)

    op.create_table('embedding_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('retriever_trace_id', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(length=255), nullable=True),
    sa.Column('embedding_dimension', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['retriever_trace_id'], ['retriever_traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('embedding_traces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_embedding_traces_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_embedding_traces_model', ['embedding_model'], unique=False)
        batch_op.create_index(batch_op.f('ix_embedding_traces_retriever_trace_id'), ['retriever_trace_id'], unique=True)

    op.create_table('retrieved_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('retriever_trace_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=255), nullable=True),
    sa.Column('document_name', sa.String(length=512), nullable=True),
    sa.Column('document_source', sa.String(length=512), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['retriever_trace_id'], ['retriever_traces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retrieved_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retrieved_documents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_retrieved_documents_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retrieved_documents_retriever_trace_id'), ['retriever_trace_id'], unique=False)
        batch_op.create_index('ix_retrieved_documents_trace_chunk', ['retriever_trace_id', 'chunk_index'], unique=False)
        batch_op.create_index('ix_retrieved_documents_trace_score', ['retriever_trace_id', 'similarity_score'], unique=False)
        batch_op.create_index('ix_retrieved_documents_trace_selected', ['retriever_trace_id', 'selected'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retrieved_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_retrieved_documents_trace_selected')
        batch_op.drop_index('ix_retrieved_documents_trace_score')
        batch_op.drop_index('ix_retrieved_documents_trace_chunk')
        batch_op.drop_index(batch_op.f('ix_retrieved_documents_retriever_trace_id'))
        batch_op.drop_index(batch_op.f('ix_retrieved_documents_document_id'))
        batch_op.drop_index(batch_op.f('ix_retrieved_documents_created_at'))

    op.drop_table('retrieved_documents')
    with op.batch_alter_table('embedding_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_embedding_traces_retriever_trace_id'))
        batch_op.drop_index('ix_embedding_traces_model')
        batch_op.drop_index(batch_op.f('ix_embedding_traces_created_at'))

    op.drop_table('embedding_traces')
    with op.batch_alter_table('tool_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_executions_step_id'))
        batch_op.drop_index(batch_op.f('ix_tool_executions_status'))
        batch_op.drop_index(batch_op.f('ix_tool_executions_created_at'))

    op.drop_table('tool_executions')
    with op.batch_alter_table('retriever_traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retriever_traces_step_id'))

    op.drop_table('retriever_traces')
    with op.batch_alter_table('memory_accesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_accesses_step_id'))

    op.drop_table('memory_accesses')
    with op.batch_alter_table('evaluation_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_evaluation_metrics_run_name')
        batch_op.drop_index(batch_op.f('ix_evaluation_metrics_evaluation_run_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_metrics_created_at'))

    op.drop_table('evaluation_metrics')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index('ix_audit_logs_org_created')
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_messages_sender_node_id'))
        batch_op.drop_index('ix_agent_messages_sender_created')
        batch_op.drop_index(batch_op.f('ix_agent_messages_reply_to_id'))
        batch_op.drop_index(batch_op.f('ix_agent_messages_receiver_node_id'))
        batch_op.drop_index('ix_agent_messages_receiver_created')
        batch_op.drop_index(batch_op.f('ix_agent_messages_message_type'))
        batch_op.drop_index(batch_op.f('ix_agent_messages_created_at'))
        batch_op.drop_index('ix_agent_messages_conversation_type')
        batch_op.drop_index(batch_op.f('ix_agent_messages_conversation_run_id'))
        batch_op.drop_index('ix_agent_messages_conversation_created')

    op.drop_table('agent_messages')
    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_executions_workflow_definition_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_executions_status'))
        batch_op.drop_index('ix_workflow_executions_definition_status')
        batch_op.drop_index(batch_op.f('ix_workflow_executions_created_at'))
        batch_op.drop_index(batch_op.f('ix_workflow_executions_conversation_run_id'))

    op.drop_table('workflow_executions')
    with op.batch_alter_table('replay_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_replay_runs_status_created')
        batch_op.drop_index(batch_op.f('ix_replay_runs_status'))
        batch_op.drop_index('ix_replay_runs_original_created')
        batch_op.drop_index(batch_op.f('ix_replay_runs_original_conversation_run_id'))
        batch_op.drop_index(batch_op.f('ix_replay_runs_created_at'))

    op.drop_table('replay_runs')
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_prompt_versions_run_version')
        batch_op.drop_index(batch_op.f('ix_prompt_versions_hash'))
        batch_op.drop_index(batch_op.f('ix_prompt_versions_created_at'))
        batch_op.drop_index(batch_op.f('ix_prompt_versions_agent_run_id'))

    op.drop_table('prompt_versions')
    with op.batch_alter_table('prompt_assemblies', schema=None) as batch_op:
        batch_op.drop_index('ix_prompt_assemblies_run')
        batch_op.drop_index(batch_op.f('ix_prompt_assemblies_created_at'))
        batch_op.drop_index(batch_op.f('ix_prompt_assemblies_agent_run_id'))

    op.drop_table('prompt_assemblies')
    with op.batch_alter_table('model_comparisons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_comparisons_created_at'))
        batch_op.drop_index(batch_op.f('ix_model_comparisons_conversation_run_id'))
        batch_op.drop_index('ix_model_comparisons_conversation_created')

    op.drop_table('model_comparisons')
    with op.batch_alter_table('evaluation_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_evaluation_runs_type_created')
        batch_op.drop_index('ix_evaluation_runs_status_created')
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_status'))
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_evaluation_type'))
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_created_at'))
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_conversation_run_id'))
        batch_op.drop_index('ix_evaluation_runs_conversation_created')

    op.drop_table('evaluation_runs')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_revoked'))
        batch_op.drop_index(batch_op.f('ix_api_keys_project_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_prefix'))
        batch_op.drop_index(batch_op.f('ix_api_keys_organization_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))

    op.drop_table('api_keys')
    with op.batch_alter_table('agent_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_steps_status'))
        batch_op.drop_index('ix_agent_steps_run_number')
        batch_op.drop_index(batch_op.f('ix_agent_steps_created_at'))
        batch_op.drop_index(batch_op.f('ix_agent_steps_agent_run_id'))

    op.drop_table('agent_steps')
    with op.batch_alter_table('agent_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_nodes_status'))
        batch_op.drop_index(batch_op.f('ix_agent_nodes_parent_node_id'))
        batch_op.drop_index(batch_op.f('ix_agent_nodes_parallel_group'))
        batch_op.drop_index(batch_op.f('ix_agent_nodes_execution_order'))
        batch_op.drop_index(batch_op.f('ix_agent_nodes_created_at'))
        batch_op.drop_index('ix_agent_nodes_conversation_status')
        batch_op.drop_index(batch_op.f('ix_agent_nodes_conversation_run_id'))
        batch_op.drop_index('ix_agent_nodes_conversation_order')
        batch_op.drop_index(batch_op.f('ix_agent_nodes_agent_run_id'))

    op.drop_table('agent_nodes')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_organization_id'))

    op.drop_table('projects')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_organization_id'))
        batch_op.drop_index('ix_memberships_org_role')

    op.drop_table('memberships')
    with op.batch_alter_table('conversation_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_conversation_runs_status_created')
        batch_op.drop_index(batch_op.f('ix_conversation_runs_status'))
        batch_op.drop_index(batch_op.f('ix_conversation_runs_request_trace_id'))
        batch_op.drop_index('ix_conversation_runs_request_created')
        batch_op.drop_index(batch_op.f('ix_conversation_runs_created_at'))

    op.drop_table('conversation_runs')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_runs_status_created')
        batch_op.drop_index(batch_op.f('ix_agent_runs_status'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_request_id'))
        batch_op.drop_index('ix_agent_runs_request_created')
        batch_op.drop_index(batch_op.f('ix_agent_runs_parent_run_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_created_at'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_agent_type'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_agent_name'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('workflow_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_definitions_workflow_name'))
        batch_op.drop_index('ix_workflow_definitions_name_version')
        batch_op.drop_index(batch_op.f('ix_workflow_definitions_created_at'))

    op.drop_table('workflow_definitions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('traces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traces_timestamp'))
        batch_op.drop_index('ix_traces_status_timestamp')
        batch_op.drop_index(batch_op.f('ix_traces_status'))
        batch_op.drop_index('ix_traces_model_timestamp')
        batch_op.drop_index(batch_op.f('ix_traces_model_name'))

    op.drop_table('traces')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
